package record

// In 2021-04 ThorNode had two bugs when withdrawing with impermanent loss.
// All the constants were generated by querying the real values from Thornode with:
// $ go run ./cmd/onetime/fetchunits [config.json]

// https://gitlab.com/thorchain/thornode/-/issues/912
// There was a bug in thornode, it withdraw units were more then the actually removed pool units,
// but the impermanent loss protection units were also added to them.
type withdrawUnitCorrection struct {
	TX          string
	ActualUnits int64
}

var withdrawUnitCorrectionsMainnet202104 = map[int64]withdrawUnitCorrection{}

var withdrawUnitCorrections *(map[int64]withdrawUnitCorrection)

func correctWithdawsImpLoss(withdraw *Withdraw, meta *Metadata) KeepOrDiscard {
	if withdrawUnitCorrections == nil {
		return Keep
	}
	correction, ok := (*withdrawUnitCorrections)[meta.BlockHeight]
	if ok {
		if correction.TX == string(withdraw.Tx) {
			withdraw.StakeUnits = correction.ActualUnits
		}
	}
	return Keep
}

func loadMainnetWithdrawImpLossUnitCorrections() {
	withdrawUnitCorrections = &withdrawUnitCorrectionsMainnet202104
	for k := range *withdrawUnitCorrections {
		WithdrawCorrections.Add(k, correctWithdawsImpLoss)
	}
}

var addInsteadWithdrawMapMainnet202104 = artificialUnitChanges{}

func loadMainnetCorrectionsWithdrawImpLoss() {
	registerArtificialDeposits(addInsteadWithdrawMapMainnet202104)
	loadMainnetWithdrawImpLossUnitCorrections()
}
