package record

// In 2021-04 ThorNode had two bugs when withdrawing with impermanent loss.
// All the constants were generated by querying the real values from Thornode with:
// $ go run ./cmd/onetime/fetchunits [config.json]

// https://gitlab.com/thorchain/thornode/-/issues/912
// There was a bug in thornode, it withdraw units were more then the actually removed pool units,
// but the impermanent loss protection units were also added to them.
type withdrawUnitCorrection struct {
	TX          string
	ActualUnits int64
}

var withdrawUnitCorrectionsMainnet202104 = map[int64]withdrawUnitCorrection{}

var withdrawUnitCorrections *(map[int64]withdrawUnitCorrection)

func correctWithdawsImpLoss(meta *Metadata) {
	// Removed: Withdraw events are no longer tracked
	_ = meta
}

func loadMainnetWithdrawImpLossUnitCorrections() {
	// Removed: Withdraw events are no longer tracked
}

// Removed: artificialUnitChanges - Stake and Withdraw events are no longer tracked

func loadMainnetCorrectionsWithdrawImpLoss() {
	// Removed: Withdraw events are no longer tracked
}
