services:
  btcq-indexer:
    build:
      context: .
      dockerfile: Dockerfile
    image: btcq-indexer
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - pg
    depends_on:
      - pg
    volumes:
      - ./config/local.json:/config.json
      - blockstore:/blockstore

  pg:
    image: timescale/timescaledb:2.13.0-pg15
    shm_size: 512m
    command: postgres -c plan_cache_mode=force_custom_plan
    environment:
      - POSTGRES_DB=btcq_indexer
      - POSTGRES_USER=btcq_indexer
      - POSTGRES_PASSWORD=password
    ports:
      - 6432:5432
    volumes:
      - pg:/var/lib/postgresql/data

  pgtest:
    image: timescale/timescaledb:2.13.0-pg15
    command: postgres -c plan_cache_mode=force_custom_plan
    environment:
      - POSTGRES_DB=btcq_indexer
      - POSTGRES_USER=btcq_indexer
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    volumes:
      - pgtest:/var/lib/postgresql/data

volumes:
  pg:
  pg2:
  pg3:
  pgtest:
  blockstore:
